name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
    - name: Update Homebrew formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        formula: fancy-login-go
        tag: ${{ github.event.release.tag_name }}
        revision: ${{ github.sha }}
        force: false